services:
  - type: web
    name: digilex-frontend
    env: static
    buildCommand: cd legal/legal/frontend && npm install && npm run build
    staticPublishPath: ./legal/legal/frontend/build
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: CI
        value: false
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache